Layout/LineLength:
  Max: 88

Style/StringLiterals:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/ClassLength:
  Enabled: False

Metrics/MethodLength:
  Enabled: False

Metrics/AbcSize:
  Enabled: False

Style/NumericPredicate:
  Enabled: False

Metrics/PerceivedComplexity:
  Enabled: False

Metrics/CyclomaticComplexity:
  Enabled: False

Style/FormatString:
  Enabled: False

Naming/MethodParameterName:
  Enabled: False
